import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Narbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/untils/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="container">
            <div className="grid grid-cols-10">
              <div className="col-span-2">
                <Navbar />
              </div>
              <div className="col-span-8"> {children}</div>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
