import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Narbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/untils/SessionProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <EdgeStoreProvider>
            <div className="">
              <div className="container bg-[#f2f2f2]/50">
                <div className="grid md:grid-cols-12 grid-cols-1">
                  <div className="xl:col-span-3 lg:col-span-3 md:col-span-4">
                    <Navbar />
                  </div>
                  <div className="xl:col-span-9 lg:col-span-9 md:col-span-8 ">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </EdgeStoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
